nextcloud_containers:

  cloud1: # Name it after your Nextcloud installation
    app_container: "nextcloud-app-container-name"
    db_container: "nextcloud-database-container-name"
    mysql_root_password: "password"
    backup_dir: "/full/path/to/directory/"
    docker_compose_file_path: "/full/path/to/docker-compose.yaml"
    number_of_backups: 5

  cloud2: # Name it after your Nextcloud installation
    app_container: "nextcloud-app-container-name"
    db_container: "nextcloud-database-container-name"
    mysql_root_password: "password"
    backup_dir: "/full/path/to/directory/"
    docker_compose_file_path: "/full/path/to/docker-compose.yaml"
    number_of_backups: 5

log:
  logging: true
  log_dir: "/path/for/logging/"

